# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: svivienn <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/02 22:39:05 by svivienn          #+#    #+#              #
#    Updated: 2019/04/02 22:39:07 by svivienn         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_display_file

all:compile

compile:
	gcc -c ft_display_file.c
	gcc -o $(NAME) ft_display_file.o

clean:
	/bin/rm -f ft_display_file.o

fclean:clean
	/bin/rm -f ft_display_file